version: '3'
services:
  web:
    build: ./web-container
    ports:
     - "80:8080"
     depends_on:
     - mongo
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  streaming:
    build: ./streaming-container
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
  cassandra:
    build: ./cassandra-container
    ports:
      - "9042:9042"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1 # change to docker-machine ip, if used on windows/mac; on linux check ifconfig -a for docker0 interface ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
