apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: web
spec:
  ports:
    - port: 9092
      name: kafka
    - port: 2181
      name: zookeeper
  selector:
    app: web
    tier: kafka
  type: ClusterIP
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: kafka
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
      tier: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
        tier: kafka
    spec:
      containers:
      - image: wurstmeister/kafka
        name: kafka
        ports:
        - containerPort: 9092
          name: kafka
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: localhost:2181
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka
        - name: KAFKA_PORT
          value: "9092"
      - image: wurstmeister/zookeeper
        name: zookeeper
        ports:
        - containerPort: 2181
          name: zookeeper
