apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: web
spec:
  ports:
    - port: 27017
  selector:
    app: web
    tier: mongo
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  labels:
    app: web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mongo
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
      tier: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
        tier: mongo
    spec:
      containers:
      - image: mongo:latest
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim