apiVersion: v1
kind: Service
metadata:
  name: streaming
  labels:
    app: web
spec:
  ports:
    - port: 8080
  selector:
    app: web
    tier: streaming
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
      tier: streaming
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
        tier: streaming
    spec:
      containers:
      - image: smartstorm/streaming
        name: streaming
        ports:
        - containerPort: 8080
          name: streaming